version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-lol
    environment:
      POSTGRES_USER: s368892
      POSTGRES_PASSWORD: wasd
      POSTGRES_DB: lol
    ports:
      - "5433:5432"
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
      - ./sql:/sql-scripts