TRUNCATE TABLE
    player_stats,
    draft,
    champion,
    match_result,
    match,
    tournament_registration,
    tournament_rules,
    tournament,
    team_membership,
    team,
    player
RESTART IDENTITY CASCADE;

INSERT INTO player (login, password_hash, nickname, email)
VALUES
    ('asd',  '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', 'Ash',   'ash@example.com'),
    ('mid_fox',      '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', 'Fox',   'fox@example.com'),
    ('jungle_wolf',  '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', 'Wolf',  'wolf@example.com'),
    ('adc_raven',    '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', 'Raven', 'raven@example.com'),
    ('support_owl',  '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', 'Owl',   'owl@example.com'),
    ('dsa','$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', 'Blaze', 'blaze@example.com'),
    ('mid_storm',    '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', 'Storm', 'storm@example.com'),
    ('jungle_bear',  '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', 'Bear',  'bear@example.com'),
    ('adc_hawk',     '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', 'Hawk',  'hawk@example.com'),
    ('support_frog', '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', 'Frog',  'frog@example.com'),
    ('111',     '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', '111',  '1@example.com'),
    ('222',     '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', '222',  '2@example.com'),
    ('333',     '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', '333',  '3@example.com'),
    ('444',     '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', '444',  '4@example.com'),
    ('555',     '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', '555',  '5@example.com'),
    ('aaa',     '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', 'aaa',  'a@example.com'),
    ('bbb',     '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', 'bbb',  'b@example.com'),
    ('ccc',     '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', 'ccc',  'c@example.com'),
    ('ddd',     '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', 'ddd',  'd@example.com'),
    ('eee',     '$2a$10$DMHIx2DWzUVTBP8dsSLcheXrILLLrAMM4T6wn7ADq.pHOlg5MESFa', 'eee',  'e@example.com');


INSERT INTO team (name, tag)
VALUES
    ('Blue Dragons', 'BD'),
    ('Red Phoenix',  'RP'),
    ('1', '1'),
    ('a', 'a');


INSERT INTO team_membership (player_id, team_id, is_captain, role)
VALUES
    (1, 1, TRUE,  'top'),
    (2, 1, FALSE, 'mid'),
    (3, 1, FALSE, 'jungle'),
    (4, 1, FALSE, 'adc'),
    (5, 1, FALSE, 'support');

INSERT INTO team_membership (player_id, team_id, is_captain, role)
VALUES
    (6, 2, TRUE,  'top'),
    (7, 2, FALSE, 'mid'),
    (8, 2, FALSE, 'jungle'),
    (9, 2, FALSE, 'adc'),
    (10,2, FALSE, 'support');

INSERT INTO team_membership (player_id, team_id, is_captain, role)
VALUES
    (11, 3, TRUE,  'top'),
    (12, 3, FALSE, 'mid'),
    (13, 3, FALSE, 'jungle'),
    (14, 3, FALSE, 'adc'),
    (15, 3, FALSE, 'support');

INSERT INTO team_membership (player_id, team_id, is_captain, role)
VALUES
    (16, 4, TRUE,  'top'),
    (17, 4, FALSE, 'mid'),
    (18, 4, FALSE, 'jungle'),
    (19, 4, FALSE, 'adc'),
    (20, 4, FALSE, 'support');

INSERT INTO champion (name)
VALUES
    ('Aatrox'),
    ('Ahri'),
    ('Akali'),
    ('Akshan'),
    ('Alistar'),
    ('Amumu'),
    ('Anivia'),
    ('Annie'),
    ('Aphelios'),
    ('Ashe'),
    ('Aurelion Sol'),
    ('Azir'),
    ('Bard'),
    ('Bel''Veth'),
    ('Blitzcrank'),
    ('Brand'),
    ('Braum'),
    ('Briar'),
    ('Caitlyn'),
    ('Camille'),
    ('Cassiopeia'),
    ('Cho''Gath'),
    ('Corki'),
    ('Darius'),
    ('Diana'),
    ('Draven'),
    ('Dr. Mundo'),
    ('Ekko'),
    ('Elise'),
    ('Evelynn'),
    ('Ezreal'),
    ('Fiddlesticks'),
    ('Fiora'),
    ('Fizz'),
    ('Galio'),
    ('Gangplank'),
    ('Garen'),
    ('Gnar'),
    ('Gragas'),
    ('Graves'),
    ('Gwen'),
    ('Hecarim'),
    ('Heimerdinger'),
    ('Hwei'),
    ('Illaoi'),
    ('Irelia'),
    ('Ivern'),
    ('Janna'),
    ('Jarvan IV'),
    ('Jax'),
    ('Jayce'),
    ('Jhin'),
    ('Jinx'),
    ('K''Sante'),
    ('Kai''Sa'),
    ('Kalista'),
    ('Karma'),
    ('Karthus'),
    ('Kassadin'),
    ('Katarina'),
    ('Kayle'),
    ('Kayn'),
    ('Kennen'),
    ('Kha''Zix'),
    ('Kindred'),
    ('Kled'),
    ('Kog''Maw'),
    ('LeBlanc'),
    ('Lee Sin'),
    ('Leona'),
    ('Lillia'),
    ('Lissandra'),
    ('Lulu'),
    ('Lux'),
    ('Malphite'),
    ('Malzahar'),
    ('Maokai'),
    ('Master Yi'),
    ('Milio'),
    ('Miss Fortune'),
    ('Mordekaiser'),
    ('Morgana'),
    ('Nami'),
    ('Nasus'),
    ('Nautilus'),
    ('Neeko'),
    ('Nidalee'),
    ('Nilah'),
    ('Nocturne'),
    ('Nunu & Willump'),
    ('Olaf'),
    ('Orianna'),
    ('Ornn'),
    ('Pantheon'),
    ('Poppy'),
    ('Pyke'),
    ('Qiyana'),
    ('Quinn'),
    ('Rakan'),
    ('Rammus'),
    ('Rek''Sai'),
    ('Renata Glasc'),
    ('Renekton'),
    ('Rengar'),
    ('Riven'),
    ('Rumble'),
    ('Ryze'),
    ('Samira'),
    ('Sejuani'),
    ('Senna'),
    ('Seraphine'),
    ('Sett'),
    ('Shaco'),
    ('Shen'),
    ('Shyvana'),
    ('Singed'),
    ('Sion'),
    ('Sivir'),
    ('Skarner'),
    ('Smolder'),
    ('Soraka'),
    ('Swain'),
    ('Sylas'),
    ('Syndra'),
    ('Tahm Kench'),
    ('Taliyah'),
    ('Talon'),
    ('Taric'),
    ('Teemo'),
    ('Thresh'),
    ('Tristana'),
    ('Trundle'),
    ('Tryndamere'),
    ('Twisted Fate'),
    ('Twitch'),
    ('Udyr'),
    ('Urgot'),
    ('Varus'),
    ('Vayne'),
    ('Veigar'),
    ('Vel''Koz'),
    ('Vex'),
    ('Vi'),
    ('Viego'),
    ('Viktor'),
    ('Vladimir'),
    ('Volibear'),
    ('Warwick'),
    ('Wukong'),
    ('Xayah'),
    ('Xerath'),
    ('Xin Zhao'),
    ('Yasuo'),
    ('Yone'),
    ('Yorick'),
    ('Yuumi'),
    ('Zac'),
    ('Zed'),
    ('Ziggs'),
    ('Zilean'),
    ('Zoe');


INSERT INTO tournament (name, description, start_date, end_date, format, status, creator_login)
VALUES
    ('LoL Summer Cup', 'Онлайн-турнир среди любительских команд', NOW() + INTERVAL '1 day', CURRENT_DATE + 1, 'single_elimination', 'planned', 'asd');

INSERT INTO tournament_rules (
    tournament_id,
    min_players_per_team,
    max_players_per_team,
    max_teams,
    draft_type,
    additional_rules
)
VALUES
    (1, 5, 7, 16, 'standard_lol', 'Играется по стандартным правилам турниров League of Legends.');

INSERT INTO tournament_registration (tournament_id, team_id, status)
VALUES
    (1, 1, 'approved'),
    (1, 2, 'approved');
